language: java

sudo: false

script: mvn -Drandomized.multiplier=10 -Dsolr.version=$SOLR_VERSION -Dlog.level=WARN clean verify

jdk:
  - oraclejdk8

env:
# see pom.xml for notes on previous versions
  - SOLR_VERSION=6.0.1
  - SOLR_VERSION=6.1.0

notifications:
  email:
    - dsmiley@apache.org
