language: java

script: mvn -Drandomized.multiplier=10 -Dsolr.version=$SOLR_VERSION -Dlog.level=WARN clean verify

jdk:
  - openjdk7
env:
  - SOLR_VERSION=5.0.0
  - SOLR_VERSION=5.1.0
#  - SOLR_VERSION=5.2.1

notifications:
  email:
    - dsmiley@apache.org
