language: java

script: mvn -Drandomized.multiplier=10 -Dsolr.version=$SOLR_VERSION -Dlog.level=WARN clean verify

jdk:
  - oraclejdk7
env:
# see pom.xml for notes on previous versions
  - SOLR_VERSION=5.3.2
  - SOLR_VERSION=5.4.1
  - SOLR_VERSION=5.5.2
  - SOLR_VERSION=6.0.1
  - SOLR_VERSION=6.1.0

notifications:
  email:
    - dsmiley@apache.org
