language: java

script: mvn -Drandomized.multiplier=10 -Dsolr.version=$SOLR_VERSION -Dlog.level=WARN clean verify

jdk:
  - openjdk6
env:
  - SOLR_VERSION=4.7.2
  - SOLR_VERSION=4.6.1
  - SOLR_VERSION=4.5.1
  - SOLR_VERSION=4.4.0
  - SOLR_VERSION=4.3.1

matrix:
  include:
    - jdk: openjdk7
      env: SOLR_VERSION=4.8.1
  include:
    - jdk: openjdk7
      env: SOLR_VERSION=4.9.1
  include:
    - jdk: openjdk7
      env: SOLR_VERSION=4.10.3

notifications:
  email:
    - dsmiley@apache.org